server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: u-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:hackathon}
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        use_sql_comments: true
        order_inserts: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:u-backend-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  s3:
    endpoint: https://s3.vn-hcm-1.vietnix.cloud
    access-key: ${AWS_S3_ACCESS_KEY:your-access-key}
    secret-key: ${AWS_S3_SECRET_KEY:your-secret-key}
    bucket-name: ${AWS_S3_BUCKET_NAME:hackathon}
    region: ${AWS_S3_REGION:vn-hcm-1}

app:
  pipeline:
    apiKey: ${APP_API_KEY:your-api-key}
  quiz:
    generation:
      url: http://172.31.99.3:8000

logging:
  level:
    root: INFO
    vn:
      vinaacademy: TRACE
      vinaacademy.security: TRACE
      vinaacademy.chat: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG